version: "3.8"

services:
  app:
    container_name: speranskiy-plugin
    image: avs85/speranskiy-plugin
    ports:
      - "80:80"
    build:
      context: .
      target: production
      args:
        - APP_LLM_MODEL=openai

    environment:
      - API_URL=https://app-test.speransky.legal/speransky/v1/