name: Build and push Docker image to Azure ACR

on:
  push:
    branches:
      - main
      - test
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Login to Azure Container Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: arc14800.azurecr.io
          username: arc14800
          password: ${{ secrets.LOYA_ACR_AZURE_PASSWORD }}

      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Get current date and time
        run: echo "BUILD_DATE=$(date +'%Y%m%d-%H%M')" >> $GITHUB_ENV

      - name: Set tag postfix based on branch
        if: github.ref == 'refs/heads/test'
        run: echo "TAG_POSTFIX=-test" >> $GITHUB_ENV
      - name: Set tag postfix to empty for main
        if: github.ref == 'refs/heads/main'
        run: echo "TAG_POSTFIX=" >> $GITHUB_ENV

      - name: Build and push Docker image to Azure ACR
        uses: docker/build-push-action@v5.0.0
        with:
          push: true
          tags: |
            arc14800.azurecr.io/${{ env.REPO }}:latest${{ env.TAG_POSTFIX }}
          file: ./Dockerfile
